### ISSUE TITLE
ניגון דמו

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#14]
ניגון דמו הוא חלק מהפונקציונליות של ניגון שיעור.
ההבדל בין שיעור פעיל לדמו הוא הסטטוס שמופיע בטבלת רכישות.
הואיל ובשלב זה אין פנייה לטבלה זו, אז כדי לדמות שיעור דמו ולבדוק את התנהגות המערכת כלפיו, הוספתי בטבלת השיעורים הנוכחית באופן זמני עמודת סטטוס.
במידה והסטטוס דמו, יש להוריד את השדות הרלוונטיים (קובץ סאונד לדמו) ולהפעיל לוגיקת דמו שמציגה חלק קטן מהשיעור.

**Comment by vzukanov** [comment]
נתן, באפיון כתוב "בקבצי הדמו יש שדה משך קובץ הסאונד. ". אני לא מצליח לאתר את השדה הזה. באיזה קובץ הוא נמצא בדיוק ומה שמו?

**Comment by natan1957** [comment]
הכוונה הייתה שבקבצי הדמו נמצא קובץ סאונד שהמשך שלו מתאים למשך ניגון הדמו. וניתן להתייחס למשך הזה.
לחילופין ניתן לחשב אותו. משך ניגון הדמו הוא 15% ממשך הקליפ ולא יותר מ 30 שניות.
משך הקליפ נמצא בשדה 
clipDuration
אפשר לומר  שלקליפ של 3:20 ומעלה, הדמו יהיה 30 שניות. אם הקליפ קצר יותר, יש לחשב 15% ממנו.

**Comment by MyMentorah** [comment]
תקין
