### ISSUE TITLE
תפריט צף לשינוי ניקוד לא רגיש למצב השיעור

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#16]
קיימים שני שיעורים האחד עם טעמים וללא ניקוד, השני עם ניקוד וללא טעמים.
בנוסף, שיעורים רבים ללא ניקוד וללא טעמים.
בולם התפריט מופיע עם כל האפשרויות.
לא תקין.
![image](https://user-images.githubusercontent.com/44430030/48675090-0ef19780-eb5d-11e8-9504-e5241feb0aab.png)
![image](https://user-images.githubusercontent.com/44430030/48675100-30528380-eb5d-11e8-9460-edfcc4ea46f8.png)
![image](https://user-images.githubusercontent.com/44430030/48675102-46f8da80-eb5d-11e8-96e8-b32772331442.png)

**Comment by vzukanov** [comment]
כרגע הלוגיקה בודקת אם קיימים קבצים עם שמות רלוונטיים ומתראה אפשרויות לפי זה. האם בשיעורים בהם אין טעמים, למשל, עדיין קיים קובץ "עם טעמים"?

**Comment by natan1957** [comment]
ארבעת הקבצים יופיעו בכל מקרה.
הלוגיקה לא צריכה להתבסס על קיום קבצים אלא על שני מתגים בוליאנים: בקובץ הג'ייסון
"isNikudIncluded": true/false
  "isTeamimIncluded": true/false,

**Comment by vzukanov** [comment]
אם שני השדות האלה בשלילי, האם זה אומר שיש רק טקסט נקי?
אם רק אחד מהם חיובי, האם יש רק את הטקסט הזה, או טקסט נקי+טקסט לפי שדה?

**Comment by MyMentorah** [comment]
כן.
טקסט נקי+ טקסט לפי שדה

טקסט נקי יהיה תמיד.

**Comment by MyMentorah** [comment]
תקין
