### ISSUE TITLE
הצגת מתגים נעולים

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#18]
הוספתי שיעור וירא הפטרה, בנוסח אשכנזי, בדיקת נעילות.
השיעור כולל מספר מתגים נעולים.
המתגים אכן ננעלים. מה שחסר זה אינדיקציה על המתג הנעול כדי שהמשתמש יידע למה המתג לא מגיב.
 אם אינני טועה, יש בקבצים הגרפיים תמונות של מתגים עם מנעול.. אפשר להשתמש.

**Comment by vzukanov** [comment]
לא הבנתי למה הכוונה וגם לא מצאתי דוגמא. צריך תמונה שתתגים איך זה נראה באייפון

**Comment by natan1957** [comment]
שלחתי לך במייל

**Comment by vzukanov** [comment]
בשלב הזה כבר אין אפשרות להוסיף תמונה למתג הזה מכיוון שהספריה בה השתמשתי לא תומכת בכך. מימשתי מתגים נעולים ישנו את צבעם לאפור.

**Comment by MyMentorah** [comment]
אפשר להפוך לאפור אבל רק את העיגול הפנימי. כך שהשטח האדום/ירוק יישאר צבוע
ויציג את המצב. העיגול הלבן יהפוך לאפור ויסמן נעילה.

**Comment by MyMentorah** [comment]
תקין
