### ISSUE TITLE
הערות על עיצוב מסך השיעור

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#2]
![image](https://user-images.githubusercontent.com/44430030/48670903-dafc7f00-eb28-11e8-954d-10a092ba981c.png)
מצורף גם תמונה של האייפון
צד ימין למעלה, במקום חץ אחורה, צריך להיות צלמית לרשימת שיעורים.
שם השיעור לא מופיע בכותרת
הטבעת הכחולה סביב כפתור ה פליי לא ממורכזת.
האפליקציה לא מזהה את פונט סתם למרות שסיפקתי אותו בטבלה.
הצבע הירוק של הפונט באייפון בהיר יותר. יש לבחור צבע דומה לזה שבאייפון

**Comment by vzukanov** [comment]
1.
באנדרואיד, בפינה השמאלית העליונה, בד"כ יש את החץ או את ההמבורגר. חץ הולך אחורה והמבורגר פותח תפריט צד.
כפתורי ניווט למסכים ספציפיים לא אמורים להיות שם. במיוחד כשהם כל-כך דומים להמבורגר. זה יבלבל את המשתמשים שילחצו על הכפתור בציפיה לראות תפריט צד.
לפי מה שאני מבין, הכפתור הזה אכן ממלא תפקיד של ניווט אחורה. לכן אני ממליץ להשאיר את החץ כדי לא לבלבל משתמשים
2.
כשהאפליקציה מנסה להשתמש בפונט
Guttman Stam
אני רואה את הודעת השגיאה הבאה:

E/JavaScript: Failed to decode downloaded font: file:///data/user/0/com.mymentorapp/files/fonts/Guttman%20Stam.ttf
E/JavaScript: OTS parsing error: OS/2: misaligned table

עקב ההודעה הזו ועקב העובדה ששאר הגופנים עובדים, סביר להיח שהבכיה היא בפורמט קובץ הגופן שאינו תקין.

**Comment by MyMentorah** [comment]
1.
בנוגע לחץ אחורה, ראשית זה צריך להיות דומה ככל הניתן לאפליקציית האייפון, שנית, זה לא תמיד אחורה.
לדוגמה, ניתן לפתוח את השיעור גם ממסך פרטי שיעור. ואני לא רוצה לחזור מהשיעור למסך פרטי שיעור אלא לרשימת השיעורים.
 2.
החלפתי בטבלה את הפונט גוטמן סתם.
נא בדוק שוב. הפונט תקין ביצעתי פרוויו וראיתי את האותיות.

**Comment by vzukanov** [comment]
הפונט עדיין לא עובד. אני רואה שבשיעורים בהם נעשה שימוש ב
Guttman David
הכל עובד כשורה.
כרגע אני נוטה לחשוב שמדובר בבעיה בפונט עצמו.
אני מסמן את הנושא הזה כטופל. תפתח כרטיס בנפרד לטובת הבעיה עם הפונט הזה ונדבר על הנושא בנפרד.

**Comment by MyMentorah** [comment]
יש להחליף בין צלמית רשימת שיעורים לאפשרויות שיעור. זה לא ישתנה בממשק אנגלית.
בתפריט להמשיך הלאה? יש להחליף הין צלמית יציאה מהשיעור לצלמית תרגול חוזר.
יש להקטין את הפונט של שים השיעור כדי שייכנסו יותר תווים.
יש למרכז עוד קצת את הטבעת סביב עיגול ה פליי.להוריד מעט (מאוד) את הטבעת בכחולה ביחס לעיגול הלבן.
כפתור עצירת הקלטה עולה גבוהה מידיי. יש להקטין את העליה, ראה באייפון.

**Comment by MyMentorah** [comment]
עניין עיצוב כפתורי הבקרה השתבש
כל  השאר תקין

**Comment by vzukanov** [comment]
איך בדיוק השתבש העיצוב?

**Comment by MyMentorah** [comment]
עיצוב רצוי מול מצוי
![image](https://user-images.githubusercontent.com/44430030/50545465-18baf000-0c1d-11e9-88ee-a96588065a5d.png)
![image](https://user-images.githubusercontent.com/44430030/50545466-2b352980-0c1d-11e9-904b-251277d49a0a.png)

**Comment by MyMentorah** [comment]
נראה לי שהורדה של הפס הכחול בלי להזיז את הלחצנים תיתן נראות יותר טובה.
![image](https://user-images.githubusercontent.com/44430030/52178388-918e0880-27d6-11e9-9afb-b08cc947b5a1.png)
