### ISSUE TITLE
סוג הדגשת מילים (סעיף 6.8) לא בוצע

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#20]
לא בוצע
(זו אופציה שלא קיימת באייפון.)

**Comment by MyMentorah** [comment]
צביעת הרקע פועלת טוב אבל הפקדים לבחירה לא נוחים.
קשה לקבוע איזה צבע ייבחר, לא ניתן לחזור בדיוק לאותו הצבע.
עדיף אובייקט שיציג פלטה עם צבעים שניתן לבחור מבניהם ולא משהו רציף.

בסגירת מתג צבעי הרקע, הצבעים שנבחרו לרקע צובעים את הטקסט. זה פיצ'ר נחמדאלא שלשם כך יש צורך לכפתור צבעי ברירת מחדל.. שיחזיר לצבעים אדום וירוק.

**Comment by vzukanov** [comment]
כפי שהסברתי, השינוי המבוקש חורג מההגדרה המופיעה באפיון. כרגע לא נעשה אותו.
