### ISSUE TITLE
איכות הסאונד ביחס לאייפון

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#21]
הסאונד המנוגן והמוקלט באפליקציה נופל מזה של אפליקציית האייפון.
וזה למרות שאיכות הסאונד של המכשירים זהה.
אני מניח שאתה יכול לזהות את זה עם האייפון שלך.
האם יש שליטה על איזה איקולייזר או פרמטרים שניתנים לנגן ולמקליט כדי לשפר את הצלילים?
איכות הצלילים היא עניין קריטי לאפליקציה שהיא כולה סטודיו להקלטות והשמעות...

**Comment by vzukanov** [comment]
יש משחק עם פרמטרים וכבר שיניתי אותם לפי ההמלצות שמצאתי באינטרנט. אני יכול לנסות לשנות עוד. להערכתי, נצטרך פשוט לשחק עם הפרמטרים עד שתהיה תוצאה סבירה כי לא מצאתי מידע לגבי שיפור הסאונד המוקלט.

**Comment by MyMentorah** [comment]
השתפר באופן משמעותי. אולי נחזור לזה בהמשך לפייו טיונינג.
