### ISSUE TITLE
ההתחלה של השמעת הקלטה מקוצצת

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#22]
כאשר המערכת משמעה את ההקלטה "רני עקרה" היא מקצצת את ההתחלה ומשמיעה למעשה "ני עקרה". יש להשמיע מההתחלה.
שולח קליפ022

**Comment by MyMentorah** [comment]
לא תקין

**Comment by MyMentorah** [comment]
שולח קליפ022ב שמשמיע את בראשית, ברכה,ספירה לבדיקות

**Comment by MyMentorah** [comment]
לא תקין

**Comment by MyMentorah** [comment]
לא תקין. הפעל את קליפ022ב ואז הפעל את אותו שיעור ותוכל לשמוע שהחלק הראשון בהקלטה נחתך.

**Comment by vzukanov** [comment]
במכשיר שלי עובד תקין ואני שומע את תחילת ההקלטה.
