### ISSUE TITLE
החלפת שפת הנחיה ללא רשת

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#29]
שפת הנחיה שמופעלת אמורה להיטען לאפליקציה ולהיות זמינה לבחירה גם ללא רשת.
זה לא עובד. ברגע שאין רשת, בניסיון להחליף שפת הנחייה, המערכת נתקעת.
באין רשת, הרשימה צריכה להציג את כל השפות שנטענו מאז ההתקנה

**Comment by MyMentorah** [comment]
רענון האפליקציה במקרה של עדכון בטבלת הנחיות קוליות, לא מתבצע.
גם במקרה של כיבוי והפעלה שלה.
שינויים נקלטים רק בהסרה והתקנה. זה לא טוב.

**Comment by MyMentorah** [comment]
ריענון שפה עובד תקין.
החלפה לשפה שטעונה כשאין רשת מתעופפת

**Comment by vzukanov** [comment]
עובד תקין אצלי גם במכשיר וגם באמולטור. 
אני גם לא רואה קריסות ממסך אפשרויות באנליטיקה. אתה זוכר איפה זה קרס בדיוק?

**Comment by MyMentorah** [comment]
עכשיו לא קרס אבל לא מחליף שפה
שולח קליפ029

**Comment by MyMentorah** [comment]
כרגע תקין
