### ISSUE TITLE
זיוף בצביעת קטעים מנוגנים

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#31]
זו תופעה שראיתי כבר אבל נעלמה והצביעה הייתה תקינה. אבל פתאום שוב הופיעה אז מיד צילמתי.
אני לא יודע להסביר למה נעלם ולמה פתאום הופיע שוב.
מצרף קליפ031

**Comment by vzukanov** [comment]
בשיעור נוח יש אי-התאמה בין הטקסט הנמצא בקובץ עם ניקוד בלבד לבין מה שמופיע בג'ייסון. לכן יש הבדלי מספר התוים והצביעה משתבשת.

ניתן לראות לפי שתי מחרוזות אלו:

 כִּֽי־רַבִּים בְּֽנֵי־שׁוֹמֵמָה מִבְּנֵי בְעוּלָה אָמַר יְהוָֽה׃
 כִּי־רַבִּים בְּנֵי־שׁוֹמֵמָה מִבְּנֵי בְעוּלָה אָמַר יְהוָה׃

במחרוזת העליונה יש תווים נוספים.

זה לא באג בתוכנה.

**Comment by MyMentorah** [comment]
כשאתה אומר ״ממה שמופיע בג׳ייסון״ אתה מתכוון למספרי התווים שמופיעים שם, או
לטקסט שמופיע שם? הטקסט לא נועד לשימוש אלא להתמצאות בג׳ייסון בלבד. מספרי
התווים, התחלה וסוף הם שקובעים. אני לא בטוח שהפורמט של הג׳ייסון מסוגל להכיל
את כל סוגי התווים שנמצאים ב
HTML.

בתאריך יום ו׳, 14 בדצמ׳ 2018 ב-11:03 מאת vzukanov <notifications@github.com

**Comment by MyMentorah** [comment]
למיטב זכרוני, אפליקציית ה iOS צובעת את זה נכון.

בתאריך יום ו׳, 14 בדצמ׳ 2018 ב-11:29 מאת My Mentor <mymentorah@gmail.com>:

**Comment by vzukanov** [comment]
מספר התוים המצויין בג'ייסון תואם אתאורך הטקסט בג'ייסון ולא תואם את אורך הטקסט בקובץ עם ניקוד.

מצאתי עוד שיעור אחד שיש בו אי התאמה "אחרי ההפטרה על ידי תן הלפמן". במקרה הזה, אי התאמה גורמת להתעופפות האפליקציה.

אני אממש מנגנון שימנע התעופפות ויחזור למסך ראשי במקרה הזה.

**Comment by MyMentorah** [comment]
אני בודק
