### ISSUE TITLE
הפעלת אפשרויות במהלך השמעת הנחיה קולית

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#40]
במהלך השמעת טוב, נתרגל שוב ו סיימת את השיעור, להתראות, אם לוחצים על אפשרויות, תפריט האפשרויות מוצג והשיעור ממשיך להתנגן.

**Comment by MyMentorah** [comment]
בכל ההנחיות הקוליות, לחיצה על אפשרויות עושה פאוז להשמעת ההנחיה הקולית ומציגה את אפשרויות.
בנתרגל שוב וב סיימת את השיעור, כפתור האפשרויות הופך לא פעיל ולא מציג את האפשרויות עד שההשמעה מסתיימת .
רצוי שההתנהגות לפחות בנתרגל שוב תהיה זהה לאחרים.

**Comment by vzukanov** [comment]
זה לא יתאפשר

**Comment by MyMentorah** [comment]
למה? מה ההבדל בין ההנחיות הקוליות השונות ?

**Comment by MyMentorah** [comment]
ניתן להכלה
