### ISSUE TITLE
גלילה בעכשיו אתה

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#47]
כאשר צביעה בסולו סגור, בתחילת עכשיו אתה יש לגלול פעם אחת את הטקסט לראש הקטע..
אחרת הוא נשאר תקוע בסוף הקטע שהושמע בשלב קודם.

**Comment by MyMentorah** [comment]
עכשיו זה גולל לראש הקטע, אבל את התלמיד גולל ידנית (כי הוא קורא..) אז הגלילה האוטומטית מחזירה לראש הקטע.
זה לא צריך לקרות. אחרי הגלילה החד פעמית לראש הקטע, אין להפעיל את האוטומט אלא פעם נוספת לגלול שוב לראש הקטע, במידת הצורך, באופן חד פעמי, בזמן התחלת ההשמעה של הקלטת התלמיד.

**Comment by vzukanov** [comment]
לפי ההגדרה המקורית של הבאג:
 "בתחילת עכשיו אתה יש לגלול פעם אחת את הטקסט לראש הקטע"
אם אני מבין נכון, זה עובד לפי ההגדרה הזו. אז מה הבעיה?

**Comment by natan1957** [comment]
הטקסט נגלל לתחילת הקטע.
קח בחשבון מצב שהטקסט הנקרא גולש מתחת למסך.
 הואיל והתלמיד קורא (ואין צביעה וגלילת מילים), כשהוא מגיע לסוף המסך הוא יגלול ידנית כדי לחשוף את המשך הטקסט הנקרא.
ברגע זה תחילת הקטע נדחף כלפי מעלה ויוצא מהגבול העליון של המסך.
כשהאפליקציה מבחינה בזה, היא גוללת חזרה ומחזירה את ראש הקטע לראש המסך. וזה מה שלא צריך לקרות.
יש להפסיק את האוטומט לאחר הגלילה לראש הקטע ולהפעיל אותו שוב ב"הקשב לעצמך" לגלילה חד פעמית כדי שוב להגיע לתחילת הקטע.
