### ISSUE TITLE
בחירת שפה

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#50]
צלמית העולם לא נראית טוב, אני שולח לך במייל צלמית אחרת עם רקע שקוף.
יש לצמצם את הרווחים בין השורות של רשימת השפות.
יש למרכז את שמות השפות
האם רוחב הרשימה רגיש לאורך התוכן-שמות השפות?
איך זה שאני בוחר עברית היברו ובבחירה מופע עברית בלבד?
![image](https://user-images.githubusercontent.com/44430030/51195689-46c75200-18f6-11e9-9ef3-f6f839b572f2.png)

**Comment by vzukanov** [comment]
לא יתאפשר לצמצם את הרווחים בין השורות ולמרכז.
לא קיבלתי צלמית עולם מעודכנת.

**Comment by natan1957** [comment]
שלחתי  צלמית עולם.
למה לא ניתן למרכז?

**Comment by MyMentorah** [comment]
צריך לשפר את הויזואליות של הרשימה.
כמו לדוגמה, שוליים מימין לטקסטים כדי שלא יהיו צמודים לקן הימני, הקטנת רווחים וכו'.
זה הדבר הראשון שהמשתמש רואה וזה נראה לא טוב.

**Comment by vzukanov** [comment]
שיפורים אסתטיים אינם תקלות
