### ISSUE TITLE
מסך הגדרות אפליקציה

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#56]
חסרה כותרת מסך
צלמית צריכה להפנות לתפריט ראשי ולא לרשימת שיעורים
בממשק עברי, בהפעלה ראשונה כיוון המסך הפוך מעברית. רק אחרי שינוי הצגת תוכן חלופי, זה מתהפך לכיוון עברית
ברשימות בחירה, לצמצם את הרווח בין השורות או להגדיל את חלון ההצגה
שינוי מתג הצג תוכן חלופי גורם להבהוב המסך ולמתג ניגון ידני לזגזג
שורת בחירת שפה צריכה להיות כמו שאר השורות הפרמטרים, שם פרמטר ורשימת בחירה נפתחת . ליד השם להוסיף באופן קבוע אייקון עולם
![image](https://user-images.githubusercontent.com/44430030/51424904-2db3ef00-1bdd-11e9-9cad-6b7a48d8297b.png)
חלק מהסטריניגים הוחלפו לאלה של הגדרות שיעור. להחליף מפתחות סטרינג של הכותרות הבאות:
הדגשת מילים
IPHONE_STRING_appsettings_showhighlightedwords
ניגון חוזר מתחיל מ
IPHONE_STRING_appsettings_lessonstartfrom
שמור הקלטות תלמיד
IPHONE_STRING_appsettings_saveuseraudio
שמור הקלטות מורה+תלמיד
IPHONE_STRING_appsettings_saveteacheranduser

אין שורת יציאה - לוג אאוט
ברירת המחדל בהצגת תוכן כלופי היא לא. המתג צריך להיות אדום
בכניסה למסך, חלק מהמתגים מזגזגים ימינה וחזרה שמאלה. יש לבטל את זה.
גודל הטקסט של רשימות הבחירה לא יכול להיות גדול מאשר של שם הפרמטר.
ברשימת בחירת עולם, שמות העולמות לא מגיעים מטבלת הסטרינגים לפי אפיון ריבוי שפות.
רשימת העולמות לא ממויינת לפי שדה אורדר.
כשאני בוחר ברשימה הדגמה-דמו הוא מציג רק דמו
![image](https://user-images.githubusercontent.com/44430030/51425375-e5e49600-1be3-11e9-9ecd-35f2d2d38d35.png)
מתג הצגת תוכן חלופי ברירת מחדל היא לא, צבע צריך להיות אדום. כרגע ירוק
מתג שמירת הקלטות ברירת מחדל = שמור הקלטות תלמיד, צריך להיות ירוק, כרגע אדום.
חסר מתג הדגשת רקע (סוג הדגשת מילים) ואובייקטים לבחירת שני צבעים.  צריך שם ליד כל אובייקט: צבע רקע וצבע מילים - מטבלת הסטרינגים. ברירת מחדל המתג הוא לא - צבע אדום. מתג זה ובחירת הצבעים יהיו ברירת מחדל לשיעורים בזמן טעינה, כמו שאר המתגים בהגדרות אפליקציה.
חסרה האפשרות לבצע יציאה, לוגאאוט.
בהמשך שמתי לב שלחיצה על יציאה מבצעת לוגאאוט. הליחצה צריכה להוביל למסך יציאה ולחייב את המשתמש להקליד סיסמה.
חסר מתג מעבר סביבות עבודה, פיתוח ייצור.

**Comment by vzukanov** [comment]
הפקדים לבחירת צבע יהיו כמו במסך הגדרות הקליפ - אחד שולט על צבע כל החלק והשני על צבע החלק המנוגן.
מה השמות של המחרוזות שצריך לשים ליד הפקדים האלו?

**Comment by vzukanov** [comment]
מה בדיוק הפונקציונליות של תהליך לוגאווט עם ססמה? איך אני מוודא שהסיסמה נכונה?

**Comment by MyMentorah** [comment]
ביקשתי ממפתח האייפון לבדוק מה עשה.

**Comment by MyMentorah** [comment]
ברשימות בחירה, להשוות את אופן התצוגה והבחירה לזה שבאפשרויות שיעור. זה גם צריך להיות אחיד וזה גם מאפשר מירכוז ונראה יותר טוב.
יש גם לקבוע שוליים מימין לערכים ברשימה, כי המצב הנוכחי לא נעים לטיפול.
שינוי מתג הצג תוכן חלופי גורם להבהוב המסך.
מפתח סטרינג ניגון ידני צריך להיות:
IPHONE_STRING_appsettings_uninterruptedplaynotactive
מפתח סטרינג ניגון רצוף צריך להיות :
IPHONE_STRING_appsettings_uninterruptedplay
אין מעבר למסך יציאה לוג אאוט, הבנתי שהסתדרת עם השאלה איך לעשות את זה.. תוכניתו האיפון הסביר שהוא עושה לוגאין ברקע עם הסיסמה ואם זה מצליח אז מבצע יציאה. אם לא, מציג הודעה.
 מתג מעבר בין סביבות עבודה, פיתוח ייצור. לא מעביר ליצור
מפתח סטרינג מתג הדגשת רקע:
app_appsettings_background_highlighting
מפתח סטרינג פקד בחירת צבע של כל יחידת הלימוד:
app_appsettings_learning_unit_color
מפתח סטרינג פקד בחירת צבע מילים מנוגנות:
app_appsettings_learning_section_color
את המחרוזות יש לקבוע מעל הפקדים כי אין מקום לצידם.

**Comment by MyMentorah** [comment]
שינוי מתג הצג תוכן חלופי גורם להבהוב המסך.
ברשימות בחירה, להשוות את אופן התצוגה והבחירה לזה שבאפשרויות שיעור
