### ISSUE TITLE
רשומות זבל בטבלת משתמשים

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#57]
לבדוק האם נוצרים ע"י האפליקציה

**Comment by vzukanov** [comment]
ייתכן והיה קשור ל
anonymous login in Parse
תבדוק עכשיו

**Comment by MyMentorah** [comment]
אתמול הקמתי משתמש עם האפליקציה.
מיד לאחר מיכן נוצרה רשומת זבל.
היום הקמתי עוד משתמש ובאותו הזמן נוצרה רשומת זבל.
כפי הנראה פעילות מסוימת של האפליקציה גורמת לכך.
יכול להיות שגם בניסיונות כושלים שלא יצרו משתמש, נרשם זבל ואולי גם בעוד תהליכים
נרשם מספר מצומצם (14) של רשומות עד 10/6/18 ואז הפסקה עד 8/9/18 ומאז מבול.
![image](https://user-images.githubusercontent.com/44430030/51685204-7b25c700-1ff6-11e9-89d3-bd18da854e51.png)

**Comment by vzukanov** [comment]
כפי שאמרתי, ייתכן והיה קשור ללוג-אין אנונימי.
תבדוק בגרסה הבאה

**Comment by MyMentorah** [comment]
הרשומות אכן הפסיקו להיווצר.
יש לך אפשרות למחוק אותן מבלי למחוק משתמשים קיימים ?
הכמות גדולה והדשבורד מאפשר למחוק רק 9 בכל פעם וזה בלתי אפשרי.

**Comment by vzukanov** [comment]
אין לי אפשרות למחוק אותם
