### ISSUE TITLE
תפריט ראשי

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#60]
לא הוספת שמות לצלמיות כפי שהצעת.
פתחתי שמות בטבלת הסטרינגים ושלחתי לך.
![image](https://user-images.githubusercontent.com/44430030/51429482-31fcfe00-1c17-11e9-92bc-9f3a87a9f0c3.png)

**Comment by vzukanov** [comment]
זה לא יעבוד מכיוון שהתפריט הראשי תמיד משמאל. בשפות כמו עברית זה ייראה מאוד מכוער ומוזר.

**Comment by MyMentorah** [comment]
זה ייראה בסדר. במקרה הצורך אמלא רווחים כדי ליישר. אבל לא נראה לי שיידרש.

**Comment by MyMentorah** [comment]
מה עם זה..
