### ISSUE TITLE
מסך הקלטות

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#62]
גם אם אין הקלטות, יש להציג קווי הפרדה בין הקלטות כמו באיפון
להגדיל את הכפתור להזזת נקודת ההשמעה
שם הקלטה עדיין לא פותח
שליחת הקלטה עדיין לא פותח.
![image](https://user-images.githubusercontent.com/44430030/51437492-d2026800-1ca7-11e9-90a1-e2ccc450061a.png)
יש להדגיש שורה נוכחית כשנוגעים בה או שמפעילים את ההשמעה
![image](https://user-images.githubusercontent.com/44430030/51437777-80f47300-1cab-11e9-9f72-c144461f0e4d.png)

**Comment by vzukanov** [comment]
![image](https://user-images.githubusercontent.com/26735137/51917635-a0e11080-23e8-11e9-9501-c4fc80fd4ba9.png)
מאיפה באים הנתונים האלו?

**Comment by vzukanov** [comment]
האם השמות שמוצגים ברשימה הם השמות של הקבצים?

**Comment by MyMentorah** [comment]
כאשר אתה מכין את רשימת השיעורים להצגה, ואתה הולך לטבלת קטגוריה1 וקטגוריה2
כדי להביא את שדות ב אורדר, כדי למיין, אז אתה מביא גם את שם הקטגוריה האנגלי
והעברי. בניית שם ההקלטה אתה משתמש בשמות הרלוונטיים על פי שפת הממשק הנוכחית,
אנגלית-אז אנגלית ולא אנגלית אז עברית.

בתאריך יום ג׳, 29 בינו׳ 2019 ב-17:17 מאת vzukanov <notifications@github.com

**Comment by vzukanov** [comment]
לפי האפיון השמות הם לפי שפת התוכן ולא שפת הממשק וזה מה שמימשתי.

**Comment by MyMentorah** [comment]
גם טוב..
