### ISSUE TITLE
עבודה ללא רשת

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#65]
עבודה ללא רשת לא נבדקה.
מבדיקת פעולות בסיסיות כמו להוריד שיעור או להפעיל שיעור טעון, נראה כי תכונה זו לא מוכנה לבדיקה.
כל עניין העבודה ללא רשת ייבדק לאחר תיקון התקלות/חוסרים בעבודה עם רשת.

**Comment by vzukanov** [comment]
האפליקציה אמורה לעבוד ללא רשת. אם יש בעיה ספציפית - תפתח באג ספציפי

**Comment by MyMentorah** [comment]
נושא זה נפתח בטיקט אחר
