### ISSUE TITLE
בודק עולמות

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#71]
משתמש עם הרשאה לבדוק עולם לא פעיל, לא מקבל אפשרות להיכנס אליו.
העולם הלא פעיל צריך להופיע אצלו ברשימת העולמות במסך אפשרויות.
ta4444 ta4444
אדמין צריך לקבל לרשימה את כל העולמות הקיימים. וזה לא קורה.

**Comment by vzukanov** [comment]
תתאר מה בדיוק התהליך מה הטבלאות והערכים שמשתתפים

**Comment by MyMentorah** [comment]
השדה 
worldTester 
ברשומת המשתמשים יכול להכיל מפתח (אובג'קט אי די) של רשומת עולם.
במידה ולמשתמש שעשה לוג אין יש מפתח מאוכלס בשדה זה, יש להציג לו ברשימת העולמות במסך אפשרויות אפליקציה, את העולם המצוין במפתח גם אם העולם לא בסטטוס אקטיב.
זה כדי לאפשר לו לבדוק את העולם לפני שמאקטבים אותו לכולם
![image](https://user-images.githubusercontent.com/44430030/51677201-786ca700-1fe1-11e9-9cc5-c85160c3fe52.png)

**Comment by MyMentorah** [comment]
אם המשתמש אדמין, יש להציג לו את כל העולמות שבטבלה

**Comment by vzukanov** [comment]
איך אני יודע שמשתמש אדמין?

**Comment by MyMentorah** [comment]
ברשומת יוזר אדמין דאטה, בשדה יוזר רול הערך הוא אדמיניסטרטורס
![image](https://user-images.githubusercontent.com/44430030/51737961-a8c24d00-2096-11e9-9c51-4260f8a9bdec.png)
