### ISSUE TITLE
ניגון הקלטה שמורה לא עוצר

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#73]
אם עוברים לשיעורים או אפילו יוצאים מהאפליקציה, ההשמעה ממשיכה

**Comment by MyMentorah** [comment]
עדיין, אם עוברים להגדרות שיעור או שחוזרים לפרטי שיעור,  או שעוברים לשליחת הקובץ.. ההשמעה נמשכת.

**Comment by vzukanov** [comment]
האם זו רשימה מלאה של מקרים בהם ההשמעה צריכה להיעצר?
