### ISSUE TITLE
לא ברור מה ההודעה שמוצגת

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#74]
![image](https://user-images.githubusercontent.com/44430030/51601173-53f2cb00-1f0c-11e9-9740-7e73f0a3d82b.png)

**Comment by vzukanov** [comment]
זו בדיקת מכשיר. צריך שם של מחרוזת

**Comment by MyMentorah** [comment]
מכשיר חסום ?
אם כן, למה נותן לי להמשיך לאפליקציה ?

**Comment by vzukanov** [comment]
משתמש רשום במכשיר אחר. לפי האפיון צריך לתת לבחור.
מה שמות המחרוזות?

**Comment by MyMentorah** [comment]
טקסט
IPHONE_STRING_needtoreplacedevice

המשך
IPHONE_STRING_needtoreplacedeviceokbutton

בטל
IPHONE_STRING_needtoreplacedevicecancelbutton
