### ISSUE TITLE
מסך רישום

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#78]
הטקסט בכפתורי רישום וביטול מוצג באותיות גדולות קפיטל לטרס
לאחר קבלת הודעה על ריג'קט, והקשה על אוקיי, אם מקישים ביטול, האפליקציה עפה
הכנסתי אותיות עבריות לסיסמה, הרישום בוצע אבל האפליקציה עפה.
בהפעלה חוזרת היא שוב עפה. הייתי חייב להסיר ולהתקין.
ייתכן שיש לאפשר רק אותיות באנגלית וספרות. ללא סימנים מיוחדים או שפות אחרות.
לפעמים האפליקציה מאבדת את השפה ובנקודה מסוימת עפה. זה קורה לא רק ברישום, אבל כאן הצלחתי להקליט.
מצרף קליפ078
כרגע גם לא מצליח לשרוד הקמת משתמש חוקי. המשתמש מוקם אבל האפליקציה עפה ומחייבת הסרה והתקנה. מצרף קליפ078ב
מחרוזת אוקיי בהודעת אימייל לא תקין צריכה להציג או6קיי ומפתח המחרוזת הוא
IPHONE_STRING_register_email_not_valid_cancel
מחרוזת אוקיי בהודעת סיסמה לא תקינה צריכה להציג או5קיי ומפתח המחרוזת הוא
IPHONE_STRING_register_password_not_valid_cancel

**Comment by MyMentorah** [comment]
לאחר קבלת הודעה על ריג'קט, והקשה על אוקיי, אם מקישים ביטול, האפליקציה עפה
מחרוזת אוקיי בהודעת אימייל לא תקין צריכה להציג או6קיי ומפתח המחרוזת הוא
IPHONE_STRING_register_email_not_valid_cancel
מחרוזת אוקיי בהודעת סיסמה לא תקינה צריכה להציג או5קיי ומפתח המחרוזת הוא
IPHONE_STRING_register_password_not_valid_cancel

**Comment by vzukanov** [comment]
אני רואה שהקוד כבר משתמש במפתחות האלו. אולי התבלבלת עם השפה?
