### ISSUE TITLE
מסך אפשרויות

### ISSUE THREAD

**Issue by MyMentorah** [MyMentorah/AndroidApp#8]
![image](https://user-images.githubusercontent.com/44430030/48671817-5add1600-eb36-11e8-9861-768b77769a33.png)
אני יוצא מנקודת הנחה שהעיצוב של המסך הזה לא סופי וגם לא אדרוש עיצוב סופי בשלב זה. הטקסטים לא מגיעים עדיין מטבלת הטקסטים. אזכיר כמה פרטים שחסרים בעיצוב. ובנוסף כמובן בתוכן ובפונקציונליות.
אין שם מסך
אין כותרות שלבי לימוד, יחידות לימוד
אין כותרת למתג ידני/רציף. הכותרת צריכה להתחלף לפי מצב המתג
בממשק אנגלי, הכותרת טיימס (פעמים) צריכה להיות משמאל למספר.
יש להרחיק בין שורת מתגי יחידות לימוד לבין מתג ניגון ידני/רציף
כאשר מתג עכשיו ביחד סגור, אי אפשר לפתוח את הקשב לשנינו
כאשר מתג עכשיו אתה סגור, אי אפשר לפתוח את מתג הקשב לעצמך
בחירת שפת הנחייה לא פועל ולא ניתן לעבור לשפה אחרת
ניגון חוזר מתחיל מ.. לא קיים
מתג שמור הקלטות תלמיד או מורה+תלמיד לא קיים

**Comment by vzukanov** [comment]
הוספתי את הדברים הרלוונטיים לשלב הזה. העיצוב הסופי ומתג "שמור הקלטה מורה או תלמיד" ייעשו בשלב הבא יחד עם הפונקציאונליות הרלוונטית.

**Comment by MyMentorah** [comment]
מתג הקשב לשנינו צריך לעקוב אחרי מתג עכשיו ביחד לשני הכיוונים
מתג הקשב לעצמך צריך לעקוב אחרי מתג עכשיו אתה לשני הכיוונים.

אם תרגול חוזר מתחיל מ  דרוך לשלב מסוים לדוגמה הקשב לי שוב, והמתגים הקשב לי שוב והלאה (עכשיו אתה) סגורים, אז למעשה עוברים ליחידת הלימוד הבאה. במקרה כזה אין להשמיע נתרגל שוב.

**Comment by vzukanov** [comment]
תיקנתי את התנהגות המתגים.
בבקשה תפתח באג נפרד על "נתרגל שוב".

**Comment by MyMentorah** [comment]
תקין
נתרגל שוב נרשם בנפרד.
